version: "3.3"
services:
  container:
    container_name: summerCampTeamAForEnvironment
    build:
      dockerfile: Dockerfile
  db:
    image: mysql:8
    container_name: summerCampTeamA
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
